"""empty message

Revision ID: 861a4bf3c010
Revises: 
Create Date: 2021-11-27 02:55:50.343694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861a4bf3c010'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment', sa.String(length=12), nullable=True),
    sa.Column('parent_post', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('author', sa.String(length=8), nullable=False),
    sa.Column('filename', sa.String(length=20), nullable=False),
    sa.Column('parent_post', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(length=12), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_post', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('student_number', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    op.drop_table('image')
    op.drop_table('comment')
    # ### end Alembic commands ###
